// src/routes/game/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import { getDrinkName } from '$lib/rules/ruleEngine';

	interface Rule {
		id: string;
		text: string;
		category: string;
		baseDrink: number;
		order: number;
		isCustom?: boolean;
	}

	interface Game {
		id: string;
		title: string;
		videoTitle: string;
		videoThumbnail: string;
		intoxicationLevel: number;
		expiresAt: string;
	}

	let game: Game | null = null;
	let rules: Rule[] = [];
	let isLoading = true;
	let error = '';
	let copied = false;
	// Read-only game page - no modification allowed

	$: gameId = $page.params.id;


	onMount(async () => {
		await loadGame();
	});

	async function loadGame() {
		try {
			const response = await fetch(`/api/games/${gameId}`);
			if (!response.ok) {
				throw new Error('Game not found');
			}

			const data = await response.json();
			game = data.game;
			rules = data.rules;
		} catch (err) {
			error = 'Failed to load game';
			console.error(err);
		} finally {
			isLoading = false;
		}
	}



	async function copyShareLink() {
		const shareUrl = `${window.location.origin}/game/${gameId}`;
		try {
			await navigator.clipboard.writeText(shareUrl);
			copied = true;
			setTimeout(() => {
				copied = false;
			}, 2000);
		} catch (err) {
			console.error('Failed to copy link:', err);
		}
	}

	function formatDate(dateString: string) {
		return new Date(dateString).toLocaleDateString();
	}

	function getIntoxicationLabel(level: number): string {
		const labels = ['Tipsy', 'Buzzed', 'Drunk', 'Wasted', 'Blackout'];
		return labels[level - 1] || 'Unknown';
	}

	function getCategoryLabel(category: string): string {
		return category.charAt(0).toUpperCase() + category.slice(1);
	}


</script>

{#if isLoading}
	<div class="loading-state">
		<div class="loading"></div>
		<p>Loading your drinking game...</p>
	</div>
{:else if error}
	<div class="error-container">
		<div class="error-message">
			<svg class="error-icon" fill="currentColor" viewBox="0 0 20 20">
				<path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
			</svg>
			<div>
				<h2>Game Not Found</h2>
				<p>The game you're looking for doesn't exist or has expired.</p>
			</div>
		</div>
		<a href="/" class="btn btn-primary">Create New Game</a>
	</div>
{:else if game}
	<div class="game-page">
		<div class="game-header">
			<div class="video-info">
				<img src={game.videoThumbnail} alt={game.videoTitle} class="video-thumbnail" />
				<div class="video-details">
					<h1 class="game-title">{game.title}</h1>
					<p class="video-title">{game.videoTitle}</p>
					<div class="game-meta">
						<span class="badge badge-primary">
							🍻 {getIntoxicationLabel(game.intoxicationLevel)}
						</span>
						<span class="badge badge-secondary">
							⏰ Expires {formatDate(game.expiresAt)}
						</span>
					</div>
				</div>
			</div>

			<div class="share-section">
				<button class="btn btn-secondary" on:click={copyShareLink}>
					{copied ? '✅ Copied!' : '📋 Share Game'}
				</button>
				<p class="share-note">Share this link with your friends to play together!</p>
			</div>
		</div>

		<div class="rules-section">
			<div class="rules-header">
				<h2 class="section-title">📜 The Rules</h2>
				<p class="section-description">Follow these rules as you watch the video. Drink responsibly!</p>
			</div>
		</div>



		<div class="rules-grid-container">
			<div class="rules-grid">
				{#each rules as rule, index (rule.id)}
					<div class="rule-card" class:custom-rule={rule.isCustom}>
						{#if rule.isCustom}
							<div class="custom-badge">Custom</div>
						{/if}
						<div class="rule-header">
							<div class="rule-number">{index + 1}</div>
							<div class="drink-info">
								<span class="drink-icon">{getDrinkName(rule.baseDrink).icon}</span>
								<span class="drink-name">{getDrinkName(rule.baseDrink).name}</span>
							</div>
						</div>

						<div class="rule-content">
							<p class="rule-text">{rule.text}</p>
						</div>

						<div class="rule-footer">
							<span class="rule-category">{getCategoryLabel(rule.category)}</span>
						</div>
					</div>
				{/each}
			</div>
		</div>
	</div>
{/if}

<style>
	.loading-state {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1rem;
		padding: 4rem 2rem;
		color: #6b7280;
	}

	.error-container {
		text-align: center;
		padding: 4rem 2rem;
		max-width: 600px;
		margin: 0 auto;
	}

	.error-message {
		display: flex;
		align-items: center;
		gap: 1rem;
		background: #fef2f2;
		border: 1px solid #fecaca;
		color: #991b1b;
		padding: 1.5rem;
		border-radius: 8px;
		margin-bottom: 2rem;
		text-align: left;
	}

	.error-icon {
		width: 24px;
		height: 24px;
		flex-shrink: 0;
	}

	.error-message h2 {
		margin: 0 0 0.5rem 0;
		font-size: 1.25rem;
		font-weight: 600;
	}

	.error-message p {
		margin: 0;
		font-size: 0.875rem;
	}

	.game-page {
		max-width: 1200px;
		margin: 0 auto;
		padding: 0 1rem;
	}

	.game-header {
		display: grid;
		grid-template-columns: 1fr auto;
		gap: 2rem;
		margin-bottom: 3rem;
		align-items: start;
	}

	.video-info {
		display: flex;
		gap: 1.5rem;
		align-items: start;
	}

	.video-thumbnail {
		width: 200px;
		height: 150px;
		object-fit: cover;
		border-radius: 12px;
		border: 1px solid #e5e7eb;
		flex-shrink: 0;
	}

	.video-details {
		flex: 1;
	}

	.game-title {
		margin: 0 0 0.5rem 0;
		color: #1f2937;
		font-size: 2rem;
		font-weight: 700;
		letter-spacing: -0.025em;
	}

	.video-title {
		margin: 0 0 1rem 0;
		color: #6b7280;
		font-size: 1.125rem;
	}

	.game-meta {
		display: flex;
		gap: 0.75rem;
		flex-wrap: wrap;
	}

	.share-section {
		text-align: center;
	}

	.share-note {
		font-size: 0.875rem;
		color: #6b7280;
		margin: 0.5rem 0 0 0;
	}

	.rules-section {
		margin-bottom: 3rem;
	}

	.rules-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.section-title {
		font-size: 2rem;
		font-weight: 700;
		color: #1f2937;
		margin: 0 0 0.5rem 0;
		letter-spacing: -0.025em;
	}

	.section-description {
		font-size: 1.125rem;
		color: #6b7280;
		margin: 0;
	}



	.rules-grid-container {
		margin-bottom: 3rem;
	}

	.rules-grid {
		display: grid;
		gap: 1.5rem;
		max-width: 800px;
		margin: 0 auto;
	}

	.rule-card {
		background: #ffffff;
		border: 1px solid #e5e7eb;
		border-radius: 12px;
		padding: 1.5rem;
		position: relative;
		transition: all 0.2s ease;
		display: flex;
		flex-direction: column;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
	}

	.rule-card:hover {
		transform: translateY(-2px);
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	}

	.rule-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 1rem;
	}

	.rule-number {
		background: #3b82f6;
		color: #ffffff;
		width: 32px;
		height: 32px;
		border-radius: 50%;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		font-size: 0.875rem;
		flex-shrink: 0;
	}

	.drink-info {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.drink-icon {
		font-size: 1.25rem;
	}

	.drink-name {
		font-size: 0.875rem;
		color: #6b7280;
		font-weight: 500;
	}

	.rule-content {
		flex-grow: 1;
		margin-bottom: 1rem;
	}

	.rule-text {
		margin: 0;
		font-size: 1rem;
		line-height: 1.5;
		color: #1f2937;
	}

	.rule-footer {
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: 1rem;
		margin-top: auto;
	}

	.rule-category {
		background: #f3f4f6;
		color: #374151;
		padding: 0.25rem 0.75rem;
		border-radius: 9999px;
		font-size: 0.75rem;
		font-weight: 500;
	}



	/* Custom Rule Styling */
	.custom-rule {
		border-color: #10b981;
		background: #f0fdf4;
	}

	.custom-badge {
		background: #10b981;
		color: #ffffff;
		padding: 0.25rem 0.75rem;
		border-radius: 9999px;
		font-size: 0.75rem;
		font-weight: 500;
		position: absolute;
		top: 1rem;
		right: 1rem;
	}

	/* Modal Styles */
	.modal-overlay {
		position: fixed;
		inset: 0;
		background-color: rgba(0, 0, 0, 0.5);
		z-index: 50;
		backdrop-filter: blur(4px);
	}

	.modal-content {
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		background: #ffffff;
		padding: 2rem;
		border-radius: 12px;
		box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
		width: 90%;
		max-width: 500px;
		z-index: 50;
		border: 1px solid #e5e7eb;
	}

	.modal-title {
		margin: 0 0 1.5rem 0;
		color: #1f2937;
		font-size: 1.5rem;
		font-weight: 600;
	}

	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}

	.modal-actions {
		display: flex;
		gap: 1rem;
		justify-content: flex-end;
		margin-top: 1.5rem;
	}

	/* Responsive design */
	@media (max-width: 768px) {
		.game-header {
			grid-template-columns: 1fr;
			gap: 1.5rem;
		}

		.video-info {
			flex-direction: column;
			text-align: center;
		}

		.video-thumbnail {
			width: 100%;
			max-width: 300px;
			height: auto;
		}

		.game-title {
			font-size: 1.75rem;
		}

		.section-title {
			font-size: 1.75rem;
		}

		.rules-actions {
			flex-direction: column;
		}

		.rules-actions .btn {
			width: 100%;
		}

		.rule-header {
			flex-direction: column;
			gap: 0.75rem;
			align-items: flex-start;
		}

		.rule-footer {
			flex-direction: column;
			gap: 0.75rem;
			align-items: flex-start;
		}

		.rule-actions {
			align-self: flex-end;
		}

		.modal-content {
			margin: 1rem;
			max-width: calc(100vw - 2rem);
		}

		.form-row {
			grid-template-columns: 1fr;
		}

		.modal-actions {
			flex-direction: column;
		}

		.modal-actions .btn {
			width: 100%;
		}
	}

	@media (max-width: 480px) {
		.game-page {
			padding: 0 0.5rem;
		}

		.game-title {
			font-size: 1.5rem;
		}

		.section-title {
			font-size: 1.5rem;
		}

		.rule-card {
			padding: 1rem;
		}
	}

	/* Dark mode support */
	@media (prefers-color-scheme: dark) {
		.game-title {
			color: #f9fafb;
		}

		.video-title {
			color: #9ca3af;
		}

		.section-title {
			color: #f9fafb;
		}

		.section-description {
			color: #9ca3af;
		}

		.rule-card {
			background: #1f2937;
			border-color: #374151;
		}

		.rule-text {
			color: #f9fafb;
		}

		.drink-name {
			color: #9ca3af;
		}

		.rule-category {
			background: #374151;
			color: #d1d5db;
		}

		.action-btn {
			border-color: #4b5563;
			color: #9ca3af;
		}

		.action-btn:hover {
			background: #374151;
			border-color: #6b7280;
		}

		.custom-rule {
			background: #064e3b;
			border-color: #10b981;
		}

		.modal-content {
			background: #1f2937;
			border-color: #374151;
		}

		.modal-title {
			color: #f9fafb;
		}

		.error-message {
			background: #450a0a;
			border-color: #7f1d1d;
			color: #fca5a5;
		}
	}
</style>

// app/game/[id]/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { ErrorPanel } from '@/components/ErrorPanel';
import { RuleCard, type RuleView } from '@/components/RuleCard';

type Game = {
	id: string;
	title: string;
	videoTitle: string;
	videoThumbnail: string;
	intoxicationLevel: number;
	expiresAt: string;
};

const intoxicationLabels = ['Tipsy', 'Buzzed', 'Drunk', 'Wasted', 'Blackout'];

export default function GamePage() {
	const params = useParams();
	const gameId = params.id as string;
	const [game, setGame] = useState<Game | null>(null);
	const [rules, setRules] = useState<RuleView[]>([]);
	const [isLoading, setIsLoading] = useState(true);
	const [error, setError] = useState('');
	const [copied, setCopied] = useState(false);

	useEffect(() => {
		(async () => {
			try {
				const response = await fetch(`/api/games/${gameId}`);
				if (!response.ok) throw new Error('Game not found');
				const data = await response.json();
				setGame(data.game);
				setRules(data.rules);
			} catch {
				setError('Failed to load game');
			} finally {
				setIsLoading(false);
			}
		})();
	}, [gameId]);

	async function copyShareLink() {
		const shareUrl = `${window.location.origin}/game/${gameId}`;
		await navigator.clipboard.writeText(shareUrl);
		setCopied(true);
		setTimeout(() => setCopied(false), 2000);
	}

	if (isLoading) {
		return <LoadingSpinner label="Loading your drinking game..." />;
	}

	if (error || !game) {
		return (
			<ErrorPanel
				title="Game Not Found"
				message="The game you're looking for doesn't exist or has expired."
			/>
		);
	}

	const label = intoxicationLabels[game.intoxicationLevel - 1] || 'Unknown';

	return (
		<div className="space-y-10">
			<div className="grid gap-8 lg:grid-cols-[1fr_auto]">
				<div className="flex flex-col gap-4 sm:flex-row">
					<img
						src={game.videoThumbnail}
						alt={game.videoTitle}
						className="h-auto w-full max-w-[300px] rounded-xl border border-gray-200 object-cover dark:border-gray-700"
					/>
					<div>
						<h1 className="text-3xl font-bold text-gray-900 dark:text-white">{game.title}</h1>
						<p className="mt-2 text-lg text-gray-600 dark:text-gray-400">{game.videoTitle}</p>
						<div className="mt-4 flex flex-wrap gap-2">
							<span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-200">
								🍻 {label}
							</span>
							<span className="rounded-full bg-gray-100 px-3 py-1 text-sm text-gray-700 dark:bg-gray-700 dark:text-gray-200">
								⏰ Expires {new Date(game.expiresAt).toLocaleDateString()}
							</span>
						</div>
					</div>
				</div>
				<div className="text-center lg:text-right">
					<button
						type="button"
						onClick={copyShareLink}
						className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-gray-50 dark:border-gray-600 dark:bg-gray-800 dark:hover:bg-gray-700"
					>
						{copied ? '✅ Copied!' : '📋 Share Game'}
					</button>
					<p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
						Share this link with your friends to play together!
					</p>
				</div>
			</div>
			<div className="text-center">
				<h2 className="text-2xl font-bold">📜 The Rules</h2>
				<p className="text-gray-600 dark:text-gray-400">
					Follow these rules as you watch the video. Drink responsibly!
				</p>
			</div>
			<div className="mx-auto max-w-2xl space-y-4">
				{rules.map((rule, index) => (
					<RuleCard key={rule.id} rule={rule} index={index} />
				))}
			</div>
			<p className="text-center">
				<Link href="/" className="text-blue-600 hover:underline dark:text-blue-400">
					Create another game
				</Link>
			</p>
		</div>
	);
}
